version: '3.3'

services:
  pg_denormalized:
    build: services/pg_denormalized
    volumes:
      - ./:/tmp/db
      - pg_denormalized:/var/lib/postgresql/data
        # docker compose down
        # not enough to start from scratch;
        # also have to remove the volumes
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pass
      - PGUSER=postgres
    ports:
      - 1433:5432
        # all ports <1024 are reserved for root
  pg_normalized:
    build: services/pg_normalized
    volumes:
      - ./:/tmp/db
      - pg_normalized:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pass
      - PGUSER=postgres
    ports:
      - 1444:5432

volumes:
    pg_normalized:
    pg_denormalized:
